// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageType int32

const (
	MessageType_JOIN_GAME  MessageType = 0
	MessageType_LEAVE_GAME MessageType = 1
	MessageType_ACTION     MessageType = 2
)

var MessageType_name = map[int32]string{
	0: "JOIN_GAME",
	1: "LEAVE_GAME",
	2: "ACTION",
}

var MessageType_value = map[string]int32{
	"JOIN_GAME":  0,
	"LEAVE_GAME": 1,
	"ACTION":     2,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type Message struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=message.MessageType" json:"type,omitempty"`
	Content              []byte      `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_JOIN_GAME
}

func (m *Message) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type JoinGame struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinGame) Reset()         { *m = JoinGame{} }
func (m *JoinGame) String() string { return proto.CompactTextString(m) }
func (*JoinGame) ProtoMessage()    {}
func (*JoinGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *JoinGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinGame.Unmarshal(m, b)
}
func (m *JoinGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinGame.Marshal(b, m, deterministic)
}
func (m *JoinGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinGame.Merge(m, src)
}
func (m *JoinGame) XXX_Size() int {
	return xxx_messageInfo_JoinGame.Size(m)
}
func (m *JoinGame) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinGame.DiscardUnknown(m)
}

var xxx_messageInfo_JoinGame proto.InternalMessageInfo

func (m *JoinGame) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *JoinGame) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LeaveGame struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveGame) Reset()         { *m = LeaveGame{} }
func (m *LeaveGame) String() string { return proto.CompactTextString(m) }
func (*LeaveGame) ProtoMessage()    {}
func (*LeaveGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *LeaveGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveGame.Unmarshal(m, b)
}
func (m *LeaveGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveGame.Marshal(b, m, deterministic)
}
func (m *LeaveGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveGame.Merge(m, src)
}
func (m *LeaveGame) XXX_Size() int {
	return xxx_messageInfo_LeaveGame.Size(m)
}
func (m *LeaveGame) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveGame.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveGame proto.InternalMessageInfo

func (m *LeaveGame) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterEnum("message.MessageType", MessageType_name, MessageType_value)
	proto.RegisterType((*Message)(nil), "message.Message")
	proto.RegisterType((*JoinGame)(nil), "message.JoinGame")
	proto.RegisterType((*LeaveGame)(nil), "message.LeaveGame")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x7c, 0xb9,
	0xd8, 0x7d, 0x21, 0x4c, 0x21, 0x0d, 0x2e, 0x96, 0x92, 0xca, 0x82, 0x54, 0x09, 0x46, 0x05, 0x46,
	0x0d, 0x3e, 0x23, 0x11, 0x3d, 0x98, 0x0e, 0xa8, 0x7c, 0x48, 0x65, 0x41, 0x6a, 0x10, 0x58, 0x85,
	0x90, 0x04, 0x17, 0x7b, 0x72, 0x7e, 0x5e, 0x49, 0x6a, 0x5e, 0x89, 0x04, 0x93, 0x02, 0xa3, 0x06,
	0x4f, 0x10, 0x8c, 0xab, 0x64, 0xc3, 0xc5, 0xe1, 0x95, 0x9f, 0x99, 0xe7, 0x9e, 0x98, 0x9b, 0x2a,
	0x24, 0xc5, 0xc5, 0x51, 0x5a, 0x9c, 0x5a, 0x94, 0x97, 0x98, 0x0b, 0x31, 0x93, 0x33, 0x08, 0xce,
	0x17, 0x12, 0xe1, 0x62, 0x2d, 0xc9, 0xcf, 0x4e, 0xcd, 0x03, 0xeb, 0xe7, 0x0c, 0x82, 0x70, 0x94,
	0x14, 0xb9, 0x38, 0x7d, 0x52, 0x13, 0xcb, 0x52, 0xdd, 0x51, 0x94, 0x30, 0x22, 0x29, 0xd1, 0xb2,
	0xe0, 0xe2, 0x46, 0x72, 0x8f, 0x10, 0x2f, 0x17, 0xa7, 0x97, 0xbf, 0xa7, 0x5f, 0xbc, 0xbb, 0xa3,
	0xaf, 0xab, 0x00, 0x83, 0x10, 0x1f, 0x17, 0x97, 0x8f, 0xab, 0x63, 0x98, 0x2b, 0x84, 0xcf, 0x28,
	0xc4, 0xc5, 0xc5, 0xe6, 0xe8, 0x1c, 0xe2, 0xe9, 0xef, 0x27, 0xc0, 0x94, 0xc4, 0x06, 0xf6, 0xb9,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x43, 0x42, 0x4c, 0x0a, 0x01, 0x00, 0x00,
}
